"""
Reasoner for PLIS-1.0
输入:
  - parsed_json: parser 输出的结构化字典
  - rule_hits: rule_engine.apply_rules(...) 的输出列表
输出:
  - machine_result: dict (可序列化为 JSON)
  - markdown_report: str
功能:
  - 为每个命中规则生成 WHY（解释）
  - 基于端口/服务/paths 构建简单攻击路径 (attack_path)
  - 为每条发现生成修复建议和置信度评分
  - 支持将结果写出到文件 (json / md)
"""

import json
import datetime
from typing import List, Dict, Any


SEVERITY_WEIGHT = {
    "critical": 1.0,
    "high": 0.8,
    "medium": 0.5,
    "low": 0.2,
    "info": 0.1
}


class Reasoner:
    def __init__(self, kb_dir: str = "kb"):
        """
        kb_dir: 可选，之后用来结合 KB 给出更丰富的解释/建议（当前实现为占位）
        """
        self.kb_dir = kb_dir

    # ---------- 公共方法 ----------
    def reason(self, parsed_json: Dict[str, Any], rule_hits: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        主入口
        返回 machine-readable 结果，包含 reasoning、attack_path、summary、metadata 等
        """
        timestamp = datetime.datetime.utcnow().isoformat() + "Z"
        summary = self._summarize_hits(rule_hits)
        attack_path = self._build_attack_path(parsed_json, rule_hits)
        detailed = [self._explain_single(hit, parsed_json) for hit in rule_hits]

        machine_result = {
            "generated_at": timestamp,
            "summary": summary,
            "attack_path": attack_path,
            "findings": detailed,
            "context": parsed_json,
        }
        return machine_result

    def to_markdown(self, machine_result: Dict[str, Any]) -> str:
        """
        将 machine_result 转换成 Markdown 报告（简单 write-up）
        """
        lines = []
        header = f"# PLIS Report — {machine_result.get('generated_at')}\n"
        lines.append(header)

        # summary
        summary = machine_result.get("summary", {})
        lines.append("## Summary\n")
        lines.append(f"- Total findings: **{summary.get('total_findings', 0)}**")
        lines.append(f"- Critical: **{summary.get('by_severity', {}).get('critical', 0)}**")
        lines.append(f"- High: **{summary.get('by_severity', {}).get('high', 0)}**")
        lines.append(f"- Medium: **{summary.get('by_severity', {}).get('medium', 0)}**")
        lines.append(f"- Low: **{summary.get('by_severity', {}).get('low', 0)}**\n")

        # context (brief)
        ctx = machine_result.get("context", {})
        lines.append("## Context\n")
        ports = ctx.get("ports", [])
        services = ctx.get("services", [])
        domain = ctx.get("domain", "")
        hostname = ctx.get("hostname", "")
        lines.append(f"- Hostname: `{hostname}`")
        lines.append(f"- Domain: `{domain}`")
        lines.append(f"- Ports: `{', '.join(ports)}`")
        lines.append(f"- Services: `{', '.join(services)}`\n")

        # attack path
        lines.append("## Attack Path (inferred)\n")
        ap = machine_result.get("attack_path", [])
        if ap:
            for step in ap:
                lines.append(f"- **{step.get('step')}**: {step.get('explain')}")
        else:
            lines.append("- No attack path inferred.\n")

        # findings detailed
        lines.append("\n## Findings\n")
        for f in machine_result.get("findings", []):
            lines.append(f"### {f.get('id')} — {f.get('name')}")
            lines.append(f"- Severity: **{f.get('severity')}**")
            lines.append(f"- Confidence: **{f.get('confidence'):.2f}**")
            desc = f.get("description", "")
            if desc:
                lines.append(f"- Description: {desc}")
            if f.get("evidence"):
                lines.append("- Evidence:")
                for e in f.get("evidence", []):
                    lines.append(f"  - `{e}`")
            if f.get("why"):
                lines.append(f"- Why?: {f.get('why')}")
            if f.get("remediation"):
                lines.append(f"- Remediation: {f.get('remediation')}")
            lines.append("")  # blank line

        # footer
        lines.append("---")
        lines.append("Generated by PLIS Reasoner")
        return "\n".join(lines)

    # ---------- 内部方法 ----------
    def _summarize_hits(self, rule_hits: List[Dict[str, Any]]) -> Dict[str, Any]:
        by_sev = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
        for h in rule_hits:
            sev = (h.get("severity") or "info").lower()
            if sev not in by_sev:
                by_sev[sev] = 0
            by_sev[sev] += 1
        total = sum(by_sev.values())
        return {"total_findings": total, "by_severity": by_sev}

    def _build_attack_path(self, parsed_json: Dict[str, Any], rule_hits: List[Dict[str, Any]]) -> List[Dict[str, str]]:
        """
        简单规则：根据端口/服务 + 规则类别 推断可能的攻击步骤（近似）。
        这是启发式，不是静态证据链。以后可以接入知识库扩充。
        返回示例：
        [
          {"step": "Discovery", "explain": "Nmap shows 389/tcp (LDAP) → AD可能暴露"},
          {"step": "Credential Access", "explain": "Detected SeBackupPrivilege → 可导出 NTDS.dit"},
          ...
        ]
        """
        steps = []
        ports = parsed_json.get("ports", [])
        services = parsed_json.get("services", [])
        keywords = parsed_json.get("keywords", []) or []
        text_tags = " ".join(ports + services + keywords).lower()

        # discovery step
        if ports or services:
            steps.append({
                "step": "Discovery",
                "explain": f"Found ports/services: {', '.join(ports)}"
            })

        # LDAP / AD -> enumeration
        if any("ldap" in s.lower() for s in services) or "ldap" in text_tags:
            steps.append({
                "step": "AD Enumeration",
                "explain": "LDAP detected; enumerate users, groups, AD structure (ldapsearch / ldapenum / ldapdomaindump)."
            })

        # RDP
        if any("rdp" in p.lower() or "ms-wbt" in p.lower() for p in ports):
            steps.append({
                "step": "RDP Check",
                "explain": "RDP is open — check for weak creds or RDP-specific exploits."
            })

        # SMB
        if any("445" in p or "smb" in s.lower() for p in ports for s in services):
            steps.append({
                "step": "SMB / AD",
                "explain": "SMB present — enumerate shares, check signing, anonymous access."
            })

        # From rule hits: special-case privileges
        for hit in rule_hits:
            hid = hit.get("id", "").lower()
            if "sebackup" in hid or "sebackupprivilege" in "".join(hit.get("evidence", [])).lower():
                steps.append({
                    "step": "Privilege Escalation",
                    "explain": "SeBackupPrivilege detected — attacker can read protected files (NTDS.dit, SYSTEM) for credential extraction."
                })
            if "lfi" in hid or "file_include" in hid:
                steps.append({
                    "step": "LFI",
                    "explain": "File include indicators found — attempt to read sensitive files or pivot to RCE via local file inclusion."
                })
            if "sqli" in hid or "sql_injection" in hid:
                steps.append({
                    "step": "SQLi",
                    "explain": "SQL Injection indicators — try extracting DB schema and data using boolean/time-based techniques."
                })
            if "ssrf" in hid:
                steps.append({
                    "step": "SSRF",
                    "explain": "Potential SSRF — attempt to reach internal services (127.0.0.1, 169.254.169.254)."
                })

        # deduplicate by 'step'
        seen = set()
        dedup = []
        for s in steps:
            if s["step"] not in seen:
                dedup.append(s)
                seen.add(s["step"])
        return dedup

    def _explain_single(self, hit: Dict[str, Any], parsed_json: Dict[str, Any]) -> Dict[str, Any]:
        """
        为单个规则命中生成详细解释
        输入 hit 的结构 (示例):
        {
            "id": "LFI_PathTraversal",
            "name": "Local File Inclusion",
            "severity": "critical",
            "description": "...",
            "evidence": ["keyword: ../", "keyword: /etc/passwd"]
        }
        """
        eid = hit.get("id", hit.get("name", "unknown"))
        name = hit.get("name", "")
        severity = (hit.get("severity") or "info").lower()
        description = hit.get("description") or ""
        evidence = hit.get("evidence") or []

        # 置信度 heuristic：基于 severity weight + 证据条数
        base = SEVERITY_WEIGHT.get(severity, 0.1)
        evidence_score = min(0.9, 0.2 * len(evidence))  # 每条 evidence 提升 0.2，最多 +0.9
        confidence = min(1.0, base * 0.6 + evidence_score * 0.4)

        # 构建 why（自然语言）
        why_parts = []
        if evidence:
            why_parts.append("Evidence: " + "; ".join(evidence))
        # 如果 parsed_json 有路径或错误，加入上下文
        paths = parsed_json.get("paths", [])
        errors = parsed_json.get("errors", [])
        if paths:
            why_parts.append("Observed paths: " + ", ".join(paths))
        if errors:
            why_parts.append("Server errors: " + ", ".join(errors))

        why = " | ".join(why_parts) if why_parts else ("Rule matched: " + eid)

        # Remediation: 若规则中有 remediation 字段则优先使用，否则通用建议
        remediation = hit.get("remediation")
        if not remediation:
            remediation = self._default_remediation(eid, name, severity)

        finding = {
            "id": eid,
            "name": name,
            "severity": severity,
            "description": description,
            "evidence": evidence,
            "why": why,
            "confidence": confidence,
            "remediation": remediation
        }
        return finding

    def _default_remediation(self, eid: str, name: str, severity: str) -> str:
        """
        根据漏洞类型/名称/严重度产生通用修复建议（占位，可被 KB 覆盖）
        """
        n = (name or eid).lower()
        if "sql" in n or "sqli" in n:
            return "Use parameterized queries / prepared statements; validate and escape inputs; limit DB user privileges; enable error message suppression."
        if "xss" in n:
            return "Sanitize output, use context-aware encoding, implement CSP, and validate/escape inputs."
        if "csrf" in n:
            return "Implement anti-CSRF tokens (random, per-session), use SameSite cookies and require POST for state changes."
        if "upload" in n or "webshell" in n:
            return "Validate file types on server-side, force safe storage paths, remove executable permissions, and scan uploads."
        if "lfi" in n or "file_include" in n:
            return "Validate/normalize file paths, restrict to allowed directories, and disallow direct file names from user input."
        if "sebackup" in eid or "privilege" in n:
            return "Review user privileges; restrict SeBackupPrivilege to necessary admin/service accounts; audit backup-related accounts."
        if "ssrf" in n:
            return "Whitelist allowed outbound hosts, validate URLs, and block access to internal metadata IPs (169.254.169.254)."
        return "Investigate the finding, follow secure coding practices, and apply principle of least privilege."

    # ---------- IO helpers ----------
    def save_json(self, machine_result: Dict[str, Any], path: str):
        with open(path, "w", encoding="utf-8") as f:
            json.dump(machine_result, f, indent=2, ensure_ascii=False)

    def save_markdown(self, markdown: str, path: str):
        with open(path, "w", encoding="utf-8") as f:
            f.write(markdown)


# -------------- Demo / Quick test --------------
if __name__ == "__main__":
    # 简单示例：伪造 parsed_json + rule_hits，运行 reasoner 并输出 report
    parsed = {
        "ports": ["53/domain", "88/kerberos-sec", "389/ldap", "445/microsoft-ds?", "3389/ms-wbt-server"],
        "services": ["Simple DNS Plus", "Microsoft Windows Kerberos", "Active Directory LDAP", "Microsoft RDP"],
        "paths": ["/index.php?file=../../../../etc/passwd"],
        "errors": ["syntax error near SELECT"],
        "keywords": ["SeBackupPrivilege", "../", "ldap"]
    }

    # rule_hits 来自 rule_engine.apply_rules(...) 的模拟输出
    rule_hits = [
        {
            "id": "AD_SeBackupPrivilege",
            "name": "SeBackupPrivilege Assigned to User",
            "severity": "critical",
            "description": "User has SeBackupPrivilege",
            "evidence": ["keyword: SeBackupPrivilege"]
        },
        {
            "id": "LFI_Common_Patterns",
            "name": "Local File Inclusion Common Indicators",
            "severity": "high",
            "description": "Detected ../ and /etc/passwd",
            "evidence": ["keyword: ../", "keyword: /etc/passwd"]
        },
        {
            "id": "LDAP_Exposure",
            "name": "LDAP/AD Exposure",
            "severity": "high",
            "description": "LDAP service exposed",
            "evidence": ["keyword: ldap"]
        }
    ]

    r = Reasoner()
    result = r.reason(parsed, rule_hits)
    md = r.to_markdown(result)

    print(json.dumps(result, indent=2, ensure_ascii=False))
    print("\n--- Markdown report preview ---\n")
    print(md[:2000])  # 预览前 2000 字符
